name: pull requests

on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
      - release-*
env:
  BASE_BRANCH: origin/main
  GO_VERSION: "1.23"
  
jobs:
  pr-check:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: go test
        run: |
          go test ./...
